<template>
  <v-dialog max-width="500">
    <v-card>
      <v-card-title>
        <h3 class="text-center mt-3">Give your wishlist a name</h3>
      </v-card-title>
      <v-card-text class="mb-n7">
        <v-text-field
            v-model="wishlistName"
            control-variant="hidden"
            class="mx-auto text-center"
            max-width="370"
            height="100"
            placeholder="Wishlist name"
            variant="outlined"
        ></v-text-field>
      </v-card-text>
      <div class="d-flex justify-center">
        <v-btn
            @click="createWishlist"
            class="font-weight-bold ma-3 mb-8"
            color="#333333"
            height="55"
            width="370"
            :loading="isSaving"
            :disabled="isSaving"
        >Create
        </v-btn>
      </div>
    </v-card>
  </v-dialog>
</template>

<script setup>
import {useRouter} from "vue-router";
import {ref} from "vue";
import {saveWishList} from '@/api/client.js'

const router = useRouter();
const wishlistName = ref('');
const isSaving = ref(false);

async function createWishlist() {
  if (isSaving.value) return;
  isSaving.value = true;
  try {
    const name = wishlistName.value && wishlistName.value.trim().length > 0 ? wishlistName.value.trim() : 'New Wishlist';
    // Dummy / fallback data for missing fields
    const payload = {
      name,
      description: 'Autogenerated wishlist',
      username: 'demo-user',
      active: true,
      presentIdeas: [],
      expires: Date.now() + (1000 * 60 * 60 * 24 * 30) // +30 days
    };
    const saved = await saveWishList(payload);
    // Navigate after successful creation; prefer id if returned
    if (saved && saved.id) {
      router.push(`/create/${saved.id}`);
    } else {
      router.push(`/create/${name}`);
    }
  } catch (e) {
    console.error('Failed to create wishlist', e);
  } finally {
    isSaving.value = false;
  }
}
</script>

<style scoped>

</style>


